# Netlify configuration for UnimogCommunityHub

[build]
  # Directory to build (where package.json is)
  base = "/"
  
  # Build command - install all dependencies including devDependencies and build
  command = "npm ci --include=dev && npm run build"
  
  # Directory containing the built site
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.16.0"
  NPM_VERSION = "10"
  # Secrets scanning configuration - These are public anon keys meant to be exposed in the frontend
  SECRETS_SCAN_OMIT_PATHS = "dist/**,docs/**"
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_MAPBOX_ACCESS_TOKEN"

# Production context
[context.production]
  environment = { NODE_ENV = "production" }

# Deploy Preview context
[context.deploy-preview]
  environment = { NODE_ENV = "development" }

# Branch Deploy context
[context.branch-deploy]
  environment = { NODE_ENV = "development" }

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self)"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.mapbox.com https://cdn.jsdelivr.net blob:; style-src 'self' 'unsafe-inline' https://api.mapbox.com https://fonts.googleapis.com; img-src 'self' data: https: blob:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.mapbox.com https://api.openai.com https://events.mapbox.com https://api.openrouteservice.org https://corsproxy.io https://cors-anywhere.herokuapp.com https://api.allorigins.win https://www.rfs.nsw.gov.au; worker-src 'self' blob:; child-src 'self' blob:; frame-src 'none'; object-src 'none'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests;"

# Service worker headers
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Cache static assets with proper headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache favicon and related files
[[headers]]
  for = "/favicon*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    
[[headers]]
  for = "/images-hero/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache JavaScript chunks
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Ensure HTML files are not cached
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Environment variables (will be set in Netlify dashboard)
# VITE_SUPABASE_URL
# VITE_SUPABASE_ANON_KEY
# VITE_MAPBOX_ACCESS_TOKEN
# VITE_STRIPE_PREMIUM_MONTHLY_PRICE_ID
# VITE_STRIPE_LIFETIME_PRICE_ID