# Claude Code Agents Configuration
agents:
  enabled: true
  default_model: sonnet
  timeout: 300
  max_context_length: 200000
  
  delegation:
    auto_delegate: true
    require_confirmation: false
    max_delegation_depth: 3
    
  specializations:
    - name: code-reviewer
      triggers: ["review", "check", "audit", "pr", "pull request"]
      priority: high
      
    - name: code-simplifier
      triggers: ["simplify", "refactor", "clean", "reduce complexity"]
      priority: medium
      
    - name: security-reviewer
      triggers: ["security", "vulnerability", "exploit", "CVE", "OWASP"]
      priority: critical
      
    - name: tech-lead
      triggers: ["architecture", "design", "scale", "system"]
      priority: high
      
    - name: ux-reviewer
      triggers: ["ux", "ui", "accessibility", "user experience", "a11y"]
      priority: medium
      
    - name: test-engineer
      triggers: ["test", "testing", "coverage", "unit test", "e2e"]
      priority: high
      
    - name: database-expert
      triggers: ["database", "query", "sql", "optimization", "index"]
      priority: high
      
    - name: devops-engineer
      triggers: ["deploy", "ci/cd", "docker", "kubernetes", "pipeline"]
      priority: medium
      
  workflows:
    code_review:
      agents: [code-reviewer, security-reviewer, test-engineer]
      
    performance_optimization:
      agents: [database-expert, code-simplifier, tech-lead]
      
    feature_development:
      agents: [tech-lead, test-engineer, ux-reviewer, code-reviewer]
